
/* Copyright (c) 2024-2025 Douglas H. Summerville (dsummer@binghamton.edu) 
 *
 * Created from scraped data which is Copyright (c) 2024 Raspberry Pi
 * (Trading) Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef RP2350_IO_QSPI_H
#define RP2350_IO_QSPI_H

#include <stdint.h>

#define ALL1 ((uint32_t)0xFFFFFFFF)

typedef struct{
		uint32_t usbphy_dp_status;
		uint32_t usbphy_dp_ctrl;
		uint32_t usbphy_dm_status;
		uint32_t usbphy_dm_ctrl;
		uint32_t gpio_qspi_sclk_status;
		uint32_t gpio_qspi_sclk_ctrl;
		uint32_t gpio_qspi_ss_status;
		uint32_t gpio_qspi_ss_ctrl;
		uint32_t gpio_qspi_sd0_status;
		uint32_t gpio_qspi_sd0_ctrl;
		uint32_t gpio_qspi_sd1_status;
		uint32_t gpio_qspi_sd1_ctrl;
		uint32_t gpio_qspi_sd2_status;
		uint32_t gpio_qspi_sd2_ctrl;
		uint32_t gpio_qspi_sd3_status;
		uint32_t gpio_qspi_sd3_ctrl;
		uint32_t RSVD0[112];
		uint32_t irqsummary_proc0_secure;
		uint32_t irqsummary_proc0_nonsecure;
		uint32_t irqsummary_proc1_secure;
		uint32_t irqsummary_proc1_nonsecure;
		uint32_t irqsummary_dormant_wake_secure;
		uint32_t irqsummary_dormant_wake_nonsecure;
		uint32_t intr;
		uint32_t proc0_inte;
		uint32_t proc0_intf;
		uint32_t proc0_ints;
		uint32_t proc1_inte;
		uint32_t proc1_intf;
		uint32_t proc1_ints;
		uint32_t dormant_wake_inte;
		uint32_t dormant_wake_intf;
		uint32_t dormant_wake_ints;
		uint32_t RSVD1[880];
		uint32_t usbphy_dp_status_xor;
		uint32_t usbphy_dp_ctrl_xor;
		uint32_t usbphy_dm_status_xor;
		uint32_t usbphy_dm_ctrl_xor;
		uint32_t gpio_qspi_sclk_status_xor;
		uint32_t gpio_qspi_sclk_ctrl_xor;
		uint32_t gpio_qspi_ss_status_xor;
		uint32_t gpio_qspi_ss_ctrl_xor;
		uint32_t gpio_qspi_sd0_status_xor;
		uint32_t gpio_qspi_sd0_ctrl_xor;
		uint32_t gpio_qspi_sd1_status_xor;
		uint32_t gpio_qspi_sd1_ctrl_xor;
		uint32_t gpio_qspi_sd2_status_xor;
		uint32_t gpio_qspi_sd2_ctrl_xor;
		uint32_t gpio_qspi_sd3_status_xor;
		uint32_t gpio_qspi_sd3_ctrl_xor;
		uint32_t RSVDxor_0[112];
		uint32_t irqsummary_proc0_secure_xor;
		uint32_t irqsummary_proc0_nonsecure_xor;
		uint32_t irqsummary_proc1_secure_xor;
		uint32_t irqsummary_proc1_nonsecure_xor;
		uint32_t irqsummary_dormant_wake_secure_xor;
		uint32_t irqsummary_dormant_wake_nonsecure_xor;
		uint32_t intr_xor;
		uint32_t proc0_inte_xor;
		uint32_t proc0_intf_xor;
		uint32_t proc0_ints_xor;
		uint32_t proc1_inte_xor;
		uint32_t proc1_intf_xor;
		uint32_t proc1_ints_xor;
		uint32_t dormant_wake_inte_xor;
		uint32_t dormant_wake_intf_xor;
		uint32_t dormant_wake_ints_xor;
		uint32_t RSVDxor_1[880];
		uint32_t usbphy_dp_status_set;
		uint32_t usbphy_dp_ctrl_set;
		uint32_t usbphy_dm_status_set;
		uint32_t usbphy_dm_ctrl_set;
		uint32_t gpio_qspi_sclk_status_set;
		uint32_t gpio_qspi_sclk_ctrl_set;
		uint32_t gpio_qspi_ss_status_set;
		uint32_t gpio_qspi_ss_ctrl_set;
		uint32_t gpio_qspi_sd0_status_set;
		uint32_t gpio_qspi_sd0_ctrl_set;
		uint32_t gpio_qspi_sd1_status_set;
		uint32_t gpio_qspi_sd1_ctrl_set;
		uint32_t gpio_qspi_sd2_status_set;
		uint32_t gpio_qspi_sd2_ctrl_set;
		uint32_t gpio_qspi_sd3_status_set;
		uint32_t gpio_qspi_sd3_ctrl_set;
		uint32_t RSVDset_0[112];
		uint32_t irqsummary_proc0_secure_set;
		uint32_t irqsummary_proc0_nonsecure_set;
		uint32_t irqsummary_proc1_secure_set;
		uint32_t irqsummary_proc1_nonsecure_set;
		uint32_t irqsummary_dormant_wake_secure_set;
		uint32_t irqsummary_dormant_wake_nonsecure_set;
		uint32_t intr_set;
		uint32_t proc0_inte_set;
		uint32_t proc0_intf_set;
		uint32_t proc0_ints_set;
		uint32_t proc1_inte_set;
		uint32_t proc1_intf_set;
		uint32_t proc1_ints_set;
		uint32_t dormant_wake_inte_set;
		uint32_t dormant_wake_intf_set;
		uint32_t dormant_wake_ints_set;
		uint32_t RSVDset_1[880];
		uint32_t usbphy_dp_status_clr;
		uint32_t usbphy_dp_ctrl_clr;
		uint32_t usbphy_dm_status_clr;
		uint32_t usbphy_dm_ctrl_clr;
		uint32_t gpio_qspi_sclk_status_clr;
		uint32_t gpio_qspi_sclk_ctrl_clr;
		uint32_t gpio_qspi_ss_status_clr;
		uint32_t gpio_qspi_ss_ctrl_clr;
		uint32_t gpio_qspi_sd0_status_clr;
		uint32_t gpio_qspi_sd0_ctrl_clr;
		uint32_t gpio_qspi_sd1_status_clr;
		uint32_t gpio_qspi_sd1_ctrl_clr;
		uint32_t gpio_qspi_sd2_status_clr;
		uint32_t gpio_qspi_sd2_ctrl_clr;
		uint32_t gpio_qspi_sd3_status_clr;
		uint32_t gpio_qspi_sd3_ctrl_clr;
		uint32_t RSVDclr_0[112];
		uint32_t irqsummary_proc0_secure_clr;
		uint32_t irqsummary_proc0_nonsecure_clr;
		uint32_t irqsummary_proc1_secure_clr;
		uint32_t irqsummary_proc1_nonsecure_clr;
		uint32_t irqsummary_dormant_wake_secure_clr;
		uint32_t irqsummary_dormant_wake_nonsecure_clr;
		uint32_t intr_clr;
		uint32_t proc0_inte_clr;
		uint32_t proc0_intf_clr;
		uint32_t proc0_ints_clr;
		uint32_t proc1_inte_clr;
		uint32_t proc1_intf_clr;
		uint32_t proc1_ints_clr;
		uint32_t dormant_wake_inte_clr;
		uint32_t dormant_wake_intf_clr;
		uint32_t dormant_wake_ints_clr;
		uint32_t RSVDclr_1[880];
} IO_QSPI_REG_BLOCKS;


/*IO Registers as struct*/

#define io_qspi (*(IO_QSPI_REG_BLOCKS volatile *)0x40030000)


/*IO Registers AS MACROS*/

#define IO_QSPI_USBPHY_DP_STATUS (*(volatile uint32_t *)0x40030000)
#define IO_QSPI_USBPHY_DP_CTRL (*(volatile uint32_t *)0x40030004)
#define IO_QSPI_USBPHY_DM_STATUS (*(volatile uint32_t *)0x40030008)
#define IO_QSPI_USBPHY_DM_CTRL (*(volatile uint32_t *)0x4003000c)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS (*(volatile uint32_t *)0x40030010)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL (*(volatile uint32_t *)0x40030014)
#define IO_QSPI_GPIO_QSPI_SS_STATUS (*(volatile uint32_t *)0x40030018)
#define IO_QSPI_GPIO_QSPI_SS_CTRL (*(volatile uint32_t *)0x4003001c)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS (*(volatile uint32_t *)0x40030020)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL (*(volatile uint32_t *)0x40030024)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS (*(volatile uint32_t *)0x40030028)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL (*(volatile uint32_t *)0x4003002c)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS (*(volatile uint32_t *)0x40030030)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL (*(volatile uint32_t *)0x40030034)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS (*(volatile uint32_t *)0x40030038)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL (*(volatile uint32_t *)0x4003003c)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE (*(volatile uint32_t *)0x40030200)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE (*(volatile uint32_t *)0x40030204)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE (*(volatile uint32_t *)0x40030208)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE (*(volatile uint32_t *)0x4003020c)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE (*(volatile uint32_t *)0x40030210)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE (*(volatile uint32_t *)0x40030214)
#define IO_QSPI_INTR (*(volatile uint32_t *)0x40030218)
#define IO_QSPI_PROC0_INTE (*(volatile uint32_t *)0x4003021c)
#define IO_QSPI_PROC0_INTF (*(volatile uint32_t *)0x40030220)
#define IO_QSPI_PROC0_INTS (*(volatile uint32_t *)0x40030224)
#define IO_QSPI_PROC1_INTE (*(volatile uint32_t *)0x40030228)
#define IO_QSPI_PROC1_INTF (*(volatile uint32_t *)0x4003022c)
#define IO_QSPI_PROC1_INTS (*(volatile uint32_t *)0x40030230)
#define IO_QSPI_DORMANT_WAKE_INTE (*(volatile uint32_t *)0x40030234)
#define IO_QSPI_DORMANT_WAKE_INTF (*(volatile uint32_t *)0x40030238)
#define IO_QSPI_DORMANT_WAKE_INTS (*(volatile uint32_t *)0x4003023c)
#define IO_QSPI_USBPHY_DP_STATUS_XOR (*(volatile uint32_t *)0x40031000)
#define IO_QSPI_USBPHY_DP_CTRL_XOR (*(volatile uint32_t *)0x40031004)
#define IO_QSPI_USBPHY_DM_STATUS_XOR (*(volatile uint32_t *)0x40031008)
#define IO_QSPI_USBPHY_DM_CTRL_XOR (*(volatile uint32_t *)0x4003100c)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_XOR (*(volatile uint32_t *)0x40031010)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_XOR (*(volatile uint32_t *)0x40031014)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_XOR (*(volatile uint32_t *)0x40031018)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_XOR (*(volatile uint32_t *)0x4003101c)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_XOR (*(volatile uint32_t *)0x40031020)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_XOR (*(volatile uint32_t *)0x40031024)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_XOR (*(volatile uint32_t *)0x40031028)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_XOR (*(volatile uint32_t *)0x4003102c)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_XOR (*(volatile uint32_t *)0x40031030)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_XOR (*(volatile uint32_t *)0x40031034)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_XOR (*(volatile uint32_t *)0x40031038)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_XOR (*(volatile uint32_t *)0x4003103c)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_XOR (*(volatile uint32_t *)0x40031200)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_XOR (*(volatile uint32_t *)0x40031204)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_XOR (*(volatile uint32_t *)0x40031208)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_XOR (*(volatile uint32_t *)0x4003120c)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_XOR (*(volatile uint32_t *)0x40031210)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_XOR (*(volatile uint32_t *)0x40031214)
#define IO_QSPI_INTR_XOR (*(volatile uint32_t *)0x40031218)
#define IO_QSPI_PROC0_INTE_XOR (*(volatile uint32_t *)0x4003121c)
#define IO_QSPI_PROC0_INTF_XOR (*(volatile uint32_t *)0x40031220)
#define IO_QSPI_PROC0_INTS_XOR (*(volatile uint32_t *)0x40031224)
#define IO_QSPI_PROC1_INTE_XOR (*(volatile uint32_t *)0x40031228)
#define IO_QSPI_PROC1_INTF_XOR (*(volatile uint32_t *)0x4003122c)
#define IO_QSPI_PROC1_INTS_XOR (*(volatile uint32_t *)0x40031230)
#define IO_QSPI_DORMANT_WAKE_INTE_XOR (*(volatile uint32_t *)0x40031234)
#define IO_QSPI_DORMANT_WAKE_INTF_XOR (*(volatile uint32_t *)0x40031238)
#define IO_QSPI_DORMANT_WAKE_INTS_XOR (*(volatile uint32_t *)0x4003123c)
#define IO_QSPI_USBPHY_DP_STATUS_SET (*(volatile uint32_t *)0x40032000)
#define IO_QSPI_USBPHY_DP_CTRL_SET (*(volatile uint32_t *)0x40032004)
#define IO_QSPI_USBPHY_DM_STATUS_SET (*(volatile uint32_t *)0x40032008)
#define IO_QSPI_USBPHY_DM_CTRL_SET (*(volatile uint32_t *)0x4003200c)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_SET (*(volatile uint32_t *)0x40032010)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_SET (*(volatile uint32_t *)0x40032014)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_SET (*(volatile uint32_t *)0x40032018)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_SET (*(volatile uint32_t *)0x4003201c)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_SET (*(volatile uint32_t *)0x40032020)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_SET (*(volatile uint32_t *)0x40032024)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_SET (*(volatile uint32_t *)0x40032028)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_SET (*(volatile uint32_t *)0x4003202c)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_SET (*(volatile uint32_t *)0x40032030)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_SET (*(volatile uint32_t *)0x40032034)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_SET (*(volatile uint32_t *)0x40032038)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_SET (*(volatile uint32_t *)0x4003203c)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_SET (*(volatile uint32_t *)0x40032200)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_SET (*(volatile uint32_t *)0x40032204)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_SET (*(volatile uint32_t *)0x40032208)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_SET (*(volatile uint32_t *)0x4003220c)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_SET (*(volatile uint32_t *)0x40032210)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_SET (*(volatile uint32_t *)0x40032214)
#define IO_QSPI_INTR_SET (*(volatile uint32_t *)0x40032218)
#define IO_QSPI_PROC0_INTE_SET (*(volatile uint32_t *)0x4003221c)
#define IO_QSPI_PROC0_INTF_SET (*(volatile uint32_t *)0x40032220)
#define IO_QSPI_PROC0_INTS_SET (*(volatile uint32_t *)0x40032224)
#define IO_QSPI_PROC1_INTE_SET (*(volatile uint32_t *)0x40032228)
#define IO_QSPI_PROC1_INTF_SET (*(volatile uint32_t *)0x4003222c)
#define IO_QSPI_PROC1_INTS_SET (*(volatile uint32_t *)0x40032230)
#define IO_QSPI_DORMANT_WAKE_INTE_SET (*(volatile uint32_t *)0x40032234)
#define IO_QSPI_DORMANT_WAKE_INTF_SET (*(volatile uint32_t *)0x40032238)
#define IO_QSPI_DORMANT_WAKE_INTS_SET (*(volatile uint32_t *)0x4003223c)
#define IO_QSPI_USBPHY_DP_STATUS_CLR (*(volatile uint32_t *)0x40033000)
#define IO_QSPI_USBPHY_DP_CTRL_CLR (*(volatile uint32_t *)0x40033004)
#define IO_QSPI_USBPHY_DM_STATUS_CLR (*(volatile uint32_t *)0x40033008)
#define IO_QSPI_USBPHY_DM_CTRL_CLR (*(volatile uint32_t *)0x4003300c)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_CLR (*(volatile uint32_t *)0x40033010)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_CLR (*(volatile uint32_t *)0x40033014)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_CLR (*(volatile uint32_t *)0x40033018)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_CLR (*(volatile uint32_t *)0x4003301c)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_CLR (*(volatile uint32_t *)0x40033020)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_CLR (*(volatile uint32_t *)0x40033024)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_CLR (*(volatile uint32_t *)0x40033028)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_CLR (*(volatile uint32_t *)0x4003302c)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_CLR (*(volatile uint32_t *)0x40033030)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_CLR (*(volatile uint32_t *)0x40033034)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_CLR (*(volatile uint32_t *)0x40033038)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_CLR (*(volatile uint32_t *)0x4003303c)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_CLR (*(volatile uint32_t *)0x40033200)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_CLR (*(volatile uint32_t *)0x40033204)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_CLR (*(volatile uint32_t *)0x40033208)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_CLR (*(volatile uint32_t *)0x4003320c)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_CLR (*(volatile uint32_t *)0x40033210)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_CLR (*(volatile uint32_t *)0x40033214)
#define IO_QSPI_INTR_CLR (*(volatile uint32_t *)0x40033218)
#define IO_QSPI_PROC0_INTE_CLR (*(volatile uint32_t *)0x4003321c)
#define IO_QSPI_PROC0_INTF_CLR (*(volatile uint32_t *)0x40033220)
#define IO_QSPI_PROC0_INTS_CLR (*(volatile uint32_t *)0x40033224)
#define IO_QSPI_PROC1_INTE_CLR (*(volatile uint32_t *)0x40033228)
#define IO_QSPI_PROC1_INTF_CLR (*(volatile uint32_t *)0x4003322c)
#define IO_QSPI_PROC1_INTS_CLR (*(volatile uint32_t *)0x40033230)
#define IO_QSPI_DORMANT_WAKE_INTE_CLR (*(volatile uint32_t *)0x40033234)
#define IO_QSPI_DORMANT_WAKE_INTF_CLR (*(volatile uint32_t *)0x40033238)
#define IO_QSPI_DORMANT_WAKE_INTS_CLR (*(volatile uint32_t *)0x4003323c)

/*USBPHY_DP_STATUS Register macros*/

#define IO_QSPI_USBPHY_DP_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_USBPHY_DP_STATUS_IRQTOPROC_MASK IO_QSPI_USBPHY_DP_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_USBPHY_DP_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_USBPHY_DP_STATUS_INFROMPAD_MASK IO_QSPI_USBPHY_DP_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_USBPHY_DP_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_USBPHY_DP_STATUS_OETOPAD_MASK IO_QSPI_USBPHY_DP_STATUS_OETOPAD(ALL1)
#define IO_QSPI_USBPHY_DP_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_USBPHY_DP_STATUS_OUTTOPAD_MASK IO_QSPI_USBPHY_DP_STATUS_OUTTOPAD(ALL1)

/*USBPHY_DP_CTRL Register macros*/

#define IO_QSPI_USBPHY_DP_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_USBPHY_DP_CTRL_IRQOVER_MASK IO_QSPI_USBPHY_DP_CTRL_IRQOVER(ALL1)
#define IO_QSPI_USBPHY_DP_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_USBPHY_DP_CTRL_INOVER_MASK IO_QSPI_USBPHY_DP_CTRL_INOVER(ALL1)
#define IO_QSPI_USBPHY_DP_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_USBPHY_DP_CTRL_OEOVER_MASK IO_QSPI_USBPHY_DP_CTRL_OEOVER(ALL1)
#define IO_QSPI_USBPHY_DP_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_USBPHY_DP_CTRL_OUTOVER_MASK IO_QSPI_USBPHY_DP_CTRL_OUTOVER(ALL1)
#define IO_QSPI_USBPHY_DP_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_MASK IO_QSPI_USBPHY_DP_CTRL_FUNCSEL(ALL1)

/*USBPHY_DM_STATUS Register macros*/

#define IO_QSPI_USBPHY_DM_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_USBPHY_DM_STATUS_IRQTOPROC_MASK IO_QSPI_USBPHY_DM_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_USBPHY_DM_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_USBPHY_DM_STATUS_INFROMPAD_MASK IO_QSPI_USBPHY_DM_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_USBPHY_DM_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_USBPHY_DM_STATUS_OETOPAD_MASK IO_QSPI_USBPHY_DM_STATUS_OETOPAD(ALL1)
#define IO_QSPI_USBPHY_DM_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_USBPHY_DM_STATUS_OUTTOPAD_MASK IO_QSPI_USBPHY_DM_STATUS_OUTTOPAD(ALL1)

/*USBPHY_DM_CTRL Register macros*/

#define IO_QSPI_USBPHY_DM_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_USBPHY_DM_CTRL_IRQOVER_MASK IO_QSPI_USBPHY_DM_CTRL_IRQOVER(ALL1)
#define IO_QSPI_USBPHY_DM_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_USBPHY_DM_CTRL_INOVER_MASK IO_QSPI_USBPHY_DM_CTRL_INOVER(ALL1)
#define IO_QSPI_USBPHY_DM_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_USBPHY_DM_CTRL_OEOVER_MASK IO_QSPI_USBPHY_DM_CTRL_OEOVER(ALL1)
#define IO_QSPI_USBPHY_DM_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_USBPHY_DM_CTRL_OUTOVER_MASK IO_QSPI_USBPHY_DM_CTRL_OUTOVER(ALL1)
#define IO_QSPI_USBPHY_DM_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_MASK IO_QSPI_USBPHY_DM_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SCLK_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SCLK_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SS_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SS_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD0_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SD0_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD1_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SD1_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD2_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SD2_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL(ALL1)

/*GPIO_QSPI_SD3_STATUS Register macros*/

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC(v) (((v)&0x1)<<26)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD(v) (((v)&0x1)<<17)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD(v) (((v)&0x1)<<13)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD(v) (((v)&0x1)<<9)
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD_MASK IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD(ALL1)

/*GPIO_QSPI_SD3_CTRL Register macros*/

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER(v) (((v)&0x3)<<28)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER(v) (((v)&0x3)<<16)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER(v) (((v)&0x3)<<14)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER(v) (((v)&0x3)<<12)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER(ALL1)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL(v) (((v)&0x1f)<<0)
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_MASK IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL(ALL1)

/*IRQSUMMARY_PROC0_SECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DP(ALL1)

/*IRQSUMMARY_PROC0_NONSECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DP(ALL1)

/*IRQSUMMARY_PROC1_SECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DP(ALL1)

/*IRQSUMMARY_PROC1_NONSECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DP(ALL1)

/*IRQSUMMARY_DORMANT_WAKE_SECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DP(ALL1)

/*IRQSUMMARY_DORMANT_WAKE_NONSECURE Register macros*/

#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD3(v) (((v)&0x1)<<7)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD3_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD3(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD2(v) (((v)&0x1)<<6)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD2_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD2(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD1(v) (((v)&0x1)<<5)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD1_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD1(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD0(v) (((v)&0x1)<<4)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD0_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD0(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SS(v) (((v)&0x1)<<3)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SS_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SS(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SCLK(v) (((v)&0x1)<<2)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SCLK_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SCLK(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DM(v) (((v)&0x1)<<1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DM_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DM(ALL1)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DP(v) (((v)&0x1)<<0)
#define IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DP_MASK IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DP(ALL1)

/*INTR Register macros*/

#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_INTR_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_INTR_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_INTR_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_INTR_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_INTR_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_INTR_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_INTR_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_INTR_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_INTR_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_INTR_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_INTR_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_INTR_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_INTR_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_INTR_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_INTR_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_INTR_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_INTR_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_INTR_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_INTR_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_INTR_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC0_INTE Register macros*/

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC0_INTF Register macros*/

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC0_INTS Register macros*/

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC1_INTE Register macros*/

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC1_INTF Register macros*/

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_LOW(ALL1)

/*PROC1_INTS Register macros*/

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTE Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTF Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_LOW(ALL1)

/*DORMANT_WAKE_INTS Register macros*/

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH(v) (((v)&0x1)<<31)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW(v) (((v)&0x1)<<30)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(v) (((v)&0x1)<<29)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW(v) (((v)&0x1)<<28)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH(v) (((v)&0x1)<<27)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW(v) (((v)&0x1)<<26)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(v) (((v)&0x1)<<25)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW(v) (((v)&0x1)<<24)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH(v) (((v)&0x1)<<23)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW(v) (((v)&0x1)<<22)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(v) (((v)&0x1)<<21)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW(v) (((v)&0x1)<<20)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH(v) (((v)&0x1)<<19)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW(v) (((v)&0x1)<<18)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(v) (((v)&0x1)<<17)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW(v) (((v)&0x1)<<16)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH(v) (((v)&0x1)<<15)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW(v) (((v)&0x1)<<14)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH(v) (((v)&0x1)<<13)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW(v) (((v)&0x1)<<12)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(v) (((v)&0x1)<<11)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW(v) (((v)&0x1)<<10)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(v) (((v)&0x1)<<9)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(v) (((v)&0x1)<<8)
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_HIGH(v) (((v)&0x1)<<7)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_LOW(v) (((v)&0x1)<<6)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_HIGH(v) (((v)&0x1)<<5)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_LOW(v) (((v)&0x1)<<4)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_HIGH(v) (((v)&0x1)<<3)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_LOW(v) (((v)&0x1)<<2)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_LOW(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_HIGH(v) (((v)&0x1)<<1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_HIGH_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_HIGH(ALL1)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_LOW(v) (((v)&0x1)<<0)
#define IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_LOW_MASK IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_LOW(ALL1)

#endif

